vim.keymap.set("n", "<leader>cr", vim.lsp.buf.rename, { desc = "Rename" })
vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action, { desc = "Code Action" })
vim.keymap.set("n", "gr", require("telescope.builtin").lsp_references, { desc = "References" })
vim.keymap.set("n", "gi", require("telescope.builtin").lsp_implementations, { desc = "Implementation" })
vim.keymap.set("n", "gd", require("telescope.builtin").lsp_definitions, { desc = "Definition" })
vim.keymap.set("n", "gD", vim.lsp.buf.declaration, { desc = "Declaration" })
