local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader><space>", builtin.find_files, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>sg", builtin.live_grep, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>,", builtin.buffers, { desc = "Telescope buffers" })
vim.keymap.set("n", "<leader>sh", builtin.help_tags, { desc = "Telescope help tags" })
vim.keymap.set("n", "<leader>sk", builtin.keymaps, { desc = "Telescope keymaps" })
vim.keymap.set("n", "<leader>st", function()
	builtin.grep_string({ search = "TODO:" })
end, { desc = "Telescope TODOs" })
