local builtin = require("telescope.builtin")
local dropdown = require("telescope.themes").get_dropdown()
vim.keymap.set("n", "<leader><space>", function()
	builtin.find_files(dropdown)
end, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>sg", function()
	builtin.live_grep(dropdown)
end, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>,", function()
	builtin.buffers(dropdown)
end, { desc = "Telescope buffers" })
vim.keymap.set("n", "<leader>sh", function()
	builtin.help_tags(dropdown)
end, { desc = "Telescope help tags" })
vim.keymap.set("n", "<leader>sk", function()
	builtin.keymaps(dropdown)
end, { desc = "Telescope keymaps" })
vim.keymap.set("n", "<leader>st", function()
	builtin.grep_string({ search = "TODO:" })
end, { desc = "Telescope TODOs" })
